export const LogoFull = require('./WatchVibe.png')
export const LogoWhite = require('./WatchVibeFull-2.png')
export const LogoOrange = require('./WatchVibeOrange.png')
export const LogoShortOrange = require('./WatchVibeShortOrange.png')
export const LogoShortWhite = require('./WatchVibeShortWhite.png')